In [1]:
!pip install numpy

In [3]:
import numpy as np
#create array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2=np.array([[1,2,3,4,5]])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [6]:
##2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
##Attributes of nupy array
arr= np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("size (number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item size(in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
size (number of elements): 6
Data type: int64
Item size(in bytes): 8


In [12]:
 ##Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## elements wise addition
print("Addition:" , arr1+arr2)

## elements wise subtraction 
print("Substraction:" , arr1-arr2)

##elements wise mulpilication
print("Multiplication:", arr1* arr2)

##elements wise division
print("Division:", arr1/arr2)



Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [13]:
##Universal Function
arr=np.array([2,3,4,5,6])
##square root
print(np.sqrt(arr))
##Exponential
print(np.exp(arr))
##sine
print(np.sin(arr))
##natural log
print(np.log)

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
<ufunc 'log'>


In [16]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n" , arr)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
arr[0][0]

np.int64(1)

In [21]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [22]:
##Modify the elements 
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [25]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [26]:
## statistical conceps --Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

##calculate mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

##normaliation
normalized_data= (data-mean)/ std_dev
print("normalized data:" , normalized_data)

normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [27]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean =np.mean(data)
print("Mean:", mean)
#median
median=np.median(data)
print("Median:",median)
#Standard_deviation
std_dev=np.std(data)
print("Standard Deviation:", std_dev)

#Variance
variance=np.var(data)
print("variance:",variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
variance: 8.25


In [ ]:
##Logical Operation
data= np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([6, 7, 8])