In [4]:
import numpy as np
##Create a NumPy array of shape (5, 5) filled with random integers
array=np.random.randint(1,21 ,size=(5,5)) 
print("Original array")
print(array)

##replace array coloumn with 1
array[:,2]=1
print("modify array")
print(array)

Original array
[[18  9  6 14  2]
 [ 6  9 10 18  1]
 [13 17 11  3  3]
 [ 3 12  1 12  1]
 [ 4 16  7 16 18]]
modify array
[[18  9  1 14  2]
 [ 6  9  1 18  1]
 [13 17  1  3  3]
 [ 3 12  1 12  1]
 [ 4 16  1 16 18]]


In [6]:
##Create a NumPy array of shape (4, 4) with values from 1 to 16
array=np.arange(1,17).reshape(4,4)
print("Original array")
print(array)

##replace diagonal with 0
np.fill_diagonal(array,0)
print("Modify array")
print(array)

Original array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modify array
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [9]:
##create a NumPy array of shape (6, 6) with values from 1 to 36
array = np.arange(1,37).reshape((6,6))
print("Original array")
print(array)

##Extract the subarray
sub_array= array[2:5, 1:4]
print("Sub-array")
print(sub_array)

Original array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

#Extract the elements on the border
border_elements = np.concatenate((array[0,:], array[-1,]))